language: python
python:
- '2.7'
- '3.6'
install:
- pip install -e .
script:
- pytest
deploy:
  provider: pypi
  user: samuel
  password:
    secure: dxiz/pi+/M1DeZYX7w6orQHkxocBGswbyh//gkclDaTF231xZxD7ENPnytKNqzvdkKCzr0tzzJlCTDWYbez1PRbW87zUIVDoYg/so0isUp/yfy9UY4JAA1bY43tv7oE+zHxESJASze+bBRoe8Eg2vMCtq7ixUSz8Id44zHX+LDFy9BsDygOgjKqcHvAu+xfsOPEiKLhhXKGkofcdFNISHniCif6kJUI03VMV/RRerXzqfQXTH8Rsss06vrSwePNOVtOD+HOHXuKKnUhhKezCIanIOkLmdyIMxBzGC8mBf+NR3iiB1xsp6nE9EGxpELXfEy4SbZX/bBdZkMVnOsz5+xCZQ+7U62zg35S0VJCTvJEDJrtxYNgaPwL/1Ajoh+xncTIPy0KLYpMVkva97cZrDSTkIY9KVxPMrUDMUxgij9DcDmHh4Q8/m5AnRZRDiHp2HxyaDDWNFDdQ7UGTl2oMJWgFKeeJdz0XZsQct4KtM7jFJV2UvplZMVVjeLQZbEX0yH2zutuOmNyne3FP+4Bk41NwCoIBmbBruKgOhK6tj2g99ViO7xYWSVw3y6w5eP5IelAqfW7XBOFdem0T45ZGyVMEZwHXITfAELuHL8JXFtiQ4J4R0obxINcDo07fbFcragDAP3SfydEke93U5EjrUymEBDEgYjXDCl4We3fkEfM=
